/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-10-17 06:32:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.lang.Integer;
import java.lang.String;
import com.hit.beans.TenderBean;
import com.hit.utility.DBUtil;
import java.util.List;
import com.hit.dao.TenderDaoImpl;
import com.hit.dao.TenderDao;
import javax.servlet.annotation.WebServlet;

public final class vendorViewTender_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(11);
    _jspx_imports_classes.add("javax.servlet.annotation.WebServlet");
    _jspx_imports_classes.add("com.hit.beans.TenderBean");
    _jspx_imports_classes.add("com.hit.utility.DBUtil");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.hit.dao.TenderDaoImpl");
    _jspx_imports_classes.add("com.hit.dao.TenderDao");
    _jspx_imports_classes.add("java.lang.String");
    _jspx_imports_classes.add("java.lang.Integer");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"errorpage.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/png\" href=\"images/Banner_Hit.png\">\n");
      out.write("<!--link rel=\"shortcut icon\" type=\"image/ico\" href=\"images/hit_fevicon.ico\"-->\n");
      out.write("\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<title>Tender Works</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/annimate.css\">\n");
      out.write("<link href=\"css/font-awesome.min.css\" type=\"text/css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"css/SpryTabbedPanels.css\" type=\"text/css\" rel=\"stylesheet\">\n");
      out.write("<!--link rel=\"stylesheet\" href=\"css/styles.css\"-->\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Black+Ops+One\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<link href=\"css/bootstrap-dropdownhover.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style2.css\">\n");
      out.write("<style>\n");
      out.write("/*     th,tr{\n");
      out.write("    	height:50px;\n");
      out.write("    	border:2px black solid;\n");
      out.write("    	\n");
      out.write("    }\n");
      out.write("   \n");
      out.write("    td{\n");
      out.write("    	min-width:145px;\n");
      out.write("    	border: 2px dashed black;\n");
      out.write("    }\n");
      out.write("    table{\n");
      out.write("    	text-align:center;\n");
      out.write("    	border-radius:10px;\n");
      out.write("		border:1px red solid;\n");
      out.write("		text-align:center;\n");
      out.write("		background-color: cyan;\n");
      out.write("		margin:20px;\n");
      out.write("		color:blue;\n");
      out.write("		font-style:normal;\n");
      out.write("		font-size: 15px;\n");
      out.write("		padding:20px;\n");
      out.write("		cellpadding:10;\n");
      out.write("		cellspacing:10;\n");
      out.write("		margin-left : 0px;\n");
      out.write("    }\n");
      out.write("     */\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	");

	String user = (String) session.getAttribute("user");
	String uname = (String) session.getAttribute("username");
	String pword = (String) session.getAttribute("password");

	if (user == null || !user.equalsIgnoreCase("user") || uname.equals("") || pword.equals("")) {

		response.sendRedirect("loginFailed.jsp");

	}
	
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- Including the header of the page  -->\n");
      out.write("\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write('\n');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "vendorMenu.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("	<div class=\"clearfix hidden-sm hidden-xs\"\n");
      out.write("		style=\"color: white; background-color: green; margin-top: -15px; margin-bottom: 12px\">\n");
      out.write("		<marquee>Welcome to Tender Works</marquee>\n");
      out.write("	</div>\n");
      out.write("	<!--A green color line between header and body part-->\n");
      out.write("\n");
      out.write("	<div class=\"container-fluid\">\n");
      out.write("\n");
      out.write("		<div class=\"notice\">\n");
      out.write("			<div class=\"col-md-3\" style=\"margin-left: 1%\">\n");
      out.write("				");

				Connection con = DBUtil.provideConnection();
				
      out.write("\n");
      out.write("\n");
      out.write("				");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "notice.jsp", out, false);
      out.write("<br>\n");
      out.write("\n");
      out.write("				<!-- Next marquee starting-->\n");
      out.write("				");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "approved.jsp", out, false);
      out.write("<br>\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("			<!-- End of col-md-3-->\n");
      out.write("		</div>\n");
      out.write("		<!-- End of notice class-->\n");
      out.write("\n");
      out.write("\n");
      out.write("		<!-- Next part of same container-fluid in which galary or other information will be shown-->\n");
      out.write("\n");
      out.write("\n");
      out.write("		<div class=\"col-md-8\">\n");
      out.write("			<!-- <div class=\"marquee\" style=\"border:2px black hidden; background-color:white\">\n");
      out.write("        <h4 style=\"background-color:black; margin-top:-1.8px; margin-bottom:1px;padding: 5px; text-align: center;color:red;font-weight:bold\">\n");
      out.write("        &nbsp; <span id=\"pagetitle\">Admin Account</span></h4>pagetitle id is given here\n");
      out.write("        <div class=\"marquee-content\" style=\"align:center; padding-top:200px;min-height:750px;background-color:cyan\">\n");
      out.write("     		 -->\n");
      out.write("			<table class=\"bg-info table table-bordered table-hover bg-white\">\n");
      out.write("				<tr\n");
      out.write("					style=\"color: white; font-size: 16px; font-weight: bold; background-color: green\">\n");
      out.write("					<td>Tender Name</td>\n");
      out.write("					<td>Type</td>\n");
      out.write("					<td>Budget</td>\n");
      out.write("					<td>Location</td>\n");
      out.write("					<td>Deadline</td>\n");
      out.write("					<td>Description</td>\n");
      out.write("				</tr>\n");
      out.write("				");

				TenderDao dao = new TenderDaoImpl();
				List<TenderBean> tenderList = dao.getAllTenders();
				for (TenderBean tender : tenderList) {
					String tid = tender.getId();
					String tname = tender.getName();
					String ttype = tender.getType();
					int tprice = tender.getPrice();
					String tloc = tender.getLocation();
					java.util.Date udeadline = tender.getDeadline();
					java.sql.Date tdeadline = new java.sql.Date(udeadline.getTime());
					String tdesc = tender.getDesc();
				
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("				<tr>\n");
      out.write("					<td>");
      out.print(tname);
      out.write("</td>\n");
      out.write("					<td>");
      out.print(ttype);
      out.write("</td>\n");
      out.write("					<td>&#8377; ");
      out.print(tprice);
      out.write("</td>\n");
      out.write("					<td>");
      out.print(tloc);
      out.write("</td>\n");
      out.write("					<td>");
      out.print(tdeadline);
      out.write("</td>\n");
      out.write("					<td><textarea rows=\"2\" cols=\"45\" disabled>");
      out.print(tdesc);
      out.write("</textarea></td>\n");
      out.write("				</tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("				");

				}
				
      out.write("\n");
      out.write("			</table>\n");
      out.write("			<!-- </div>\n");
      out.write("     </div> -->\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("	<!-- End of container-fluid-->\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- <div class=\"container\" style=\"height:300px\">\n");
      out.write("	ucomment this if you want to add some space in the lower part of page\n");
      out.write("	</div> -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- Now from here the footer section starts-->\n");
      out.write("\n");
      out.write("	<!-- Including the footer of the page -->\n");
      out.write("\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
